# This is the default format.
# For more see: https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:categories/:year/:month/:day/:title

exclude: [".rvmrc", ".rbenv-version", "ReadMe.md", "Rakefile", "changelog.md", "License.md"]
highlighter: rouge

# Themes are encouraged to use these universal variables
# so be sure to set them if your theme uses them.
#
title : RmlUi Documentation
author :
  name : Michael R. P. Ragazzon
  email : michael.ragazzon@gmail.com
  github : mikke89
  twitter : nil
  feedburner : nil

# NOTE: If replacing this next line with your own URL, you likely want "https://" not "http://"
production_url : https://mikke89.github.io/RmlUiDoc
repository_url : https://github.com/mikke89/RmlUiDoc

# Tell Github to use the kramdown markdown interpreter
# (see https://help.github.com/articles/migrating-your-pages-site-from-maruku)
markdown: kramdown

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      lib_name : "RmlUi"
      lib_site : "https://github.com/mikke89/RmlUi"
      lib_ns   : "Rocket"
      lib_dir  : "Rocket"
